[hugoVersion]
  extended = true
  min = "0.80.0"
  max = ""

[[mounts]]
  source = "assets"
  target = "assets"

[[mounts]]
  source = "static"
  target = "static"

[[mounts]]
  source = "node_modules/docsearch.js"
  target = "assets/js/vendor/docsearch.js"

[[mounts]]
  source = "layouts"
  target = "layouts"

[[mounts]]
  source = "node_modules/@hyas/images/layouts"
  target = "layouts"
